/* tslint:disable */
/* eslint-disable */
/**
 * Todo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

import { ListsApi } from 'todo-list-client'
import {ITodoList, ITodoItem} from "./api"
const api = new ListsApi()

export const apiClient = {
    getLists: async () => {
        // return Promise.resolve(lists)
        // const api = new ListsApi()
        return api.listsGet()
    },
    addList: async(list : ITodoList) => {
        return api.listsPost(list)
    },
    deleteList: async(id : string) => {
        return api.listsIdDelete(id)
    },
    updateList: async(id : string, updatedList : ITodoList) => {
        return api.listsIdPut(id, updatedList)
    },
    getItem: async(id : string) => {
        return api.listsIdItemsGet(id)
    },
    addItem: async(id : string, item : ITodoItem) => {
        return api.listsIdItemsPost(id, item)
    },
    deleteItem: async(idList : string, idItem : string) => {
        return api.listsIdItemsIdDelete(idList, idItem)
    },
    updateItem: async(idList : string, idItem : string, updatedItem : ITodoItem) => {
        return api.listsIdItemsIdPut(idList, idItem, updatedItem)
    }
}